WITH TRIPS AS(
    select
    RIDE_ID,
    RIDEABLE_TYPE,
    DATE(TO_TIMESTAMP_NTZ(STARTED_AT)) AS STARTED_AT,
    START_STATION_ID,
    END_STATION_NAME,
    MEMBER_CASUAL,
    TIMESTAMPDIFF(SECOND, TO_TIMESTAMP(STARTED_AT), TO_TIMESTAMP(ENDED_AT))
    from 
    {{ source('DEMO', 'CITI_BIKE_TRIP') }}
)
select * from TRIPS